### PR TITLE
Adding option -j to allow configuration scope to be defined on command

### PR DESCRIPTION
**Pull request by dalesit**
line

## Pull Request Checklist

**Is this in reference to an existing issue?**
New PR to bring #36 up to date with as single commit

#### General

- [x] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [x] Update README with any necessary configuration snippets

- [ ] Binstubs are created if needed

- [x] RuboCop passes

- [x] Existing tests pass 

#### New Plugins

- [ ] Tests

- [ ] Add the plugin to the README

- [ ] Does it have a complete header as outlined [here](http://sensu-plugins.io/docs/developer_guidelines.html#coding-style)

### CODE REVIEW

**Comment by majormoses** [comment]
This looks good, can you provide any kind of manual or automated testing? If you are unsure how to write a test for it maybe just some log entries showing it working as intended.

**Comment by majormoses** [comment]
@dalesit any chance of you coming back to this and providing some testing artifact?

**Comment by dalesit** [comment]
I'm out of the country on leave at the moment, but back next week when I will try to get to look at it. What sort of test are you looking for? As it is following the procedure used in other plugins for passing separate configuration scopes, do any other plugins have a test for this that you could suggest as an example?

Cheers,

Joel

**Comment by majormoses** [comment]
not really a great testing for handlers, but if you want an example of what we are trending towards you can check out https://github.com/sensu-plugins/sensu-plugins-dcos it leverages test-kitchen and serverspec. These are by no means a requirement to get this done. Just some kind of log entry would be enough.

**Review by majormoses — APPROVED** [review]
LGTM

**Comment by majormoses** [comment]
released: https://rubygems.org/gems/sensu-plugins-graphite/versions/2.3.0

**Pull request merged**
