### PR TITLE
Update to handler-graphite-notify.rb

### PR DESCRIPTION
**Pull request by dalesit**
Update to post check status (0,1,2) to graphite metric instead of simply a 1 on a create action.

Update CHANGELOG.md

### CODE REVIEW

**Comment by analytically** [comment]
Would this not break existing users relying on 1 or 0 in Graphite?

**Comment by dalesit** [comment]
Well, the 0 would still be the same - on resolution, the check status would give 0, and the previous behaviour set a 0 on resolution.

The warning would still give a 1, so that would be the same, but it gives the additional data of differentiating between a warning and a critical. The critical is a 2 which is not 0 - whether it breaks behaviour or not depends upon whether something is taking an action based on it being either 1 or 0.

Personally, I can't see why you would want to lump warning and critical in together. If it is just graphing, it would be relatively easy to alter the graph to show a category of 0 or >0, if that was really a concern. This is just a metric of an alert. Increased resolution of data seems better - it is easier to aggregate data for display than to try and get better resolution when it hasn't been collected.

Do you have any means of asking whether it will break things for anyone?

**Comment by sstarcher** [comment]
It certainly changes the outward behavior and the original author documented the expectations of 0 or 1.  We should either bump up a major release of the plugin or change this to take a flag and default to the old 0,1 behavior.

**Comment by dalesit** [comment]
Changed commit to create separate handler-graphite-status.rb which is clearer that it is used to create a metric with the status of the sensu check when the state changes and also avoids being a breaking change.

**Comment by sstarcher** [comment]
thanks

**Pull request merged**
